travis:
  secure:
    BINSTAR_TOKEN: E0d2KKtL7PyzGVcx+KgbSVHe40hcuTbLV2suGQv6Z/kDaJFPJQhkJOLFTnK9Hx/9+WF5bsTNNZyQvtOMqQWzu0v8u6673MRTOzhFn7G85QDwgfsB2W30fEETX+l+Gx1p/s5K6qZvI1F7+hIdLZNE8nLQ43xND3II0eNoQOPJnEIXy3/bE6OOzyv2zvLrox5fh/e8c45y2GJdUbm2tkSn12Bg8SvyXmJKd6Loa7dIUhzQ1atX70X4IeHDIpljuciigHxPzYsCRVad7TpoPfoFSLBLhVjI8Um+tCdc7Cao2GMw3jxAtSDSdJcDTuSHiM17AK586V/hB4x0IUuqFwhewv7yoToFF8u6olSa2Ry9hx347ztUyUjwge1QF6y8FHPZTf05ct7amL5ZDAGjr6eVc/NcHJA2AmKqZOIVoKAvgVxqNPp0X0R6bBTplD7xnJLjdOhmn9RHh91PApC0XxzSuGIKQPdcr5dyKL6NxVkkZ3fwbtLdK0eEX/zf8Z7VGlDi2G2VlMKHaATbGt2qje3QL3SLUKWlMSZ29IGHfnsO0PxQex41qiMX+0qIVB1kPAc8tqI/Pig3xWMya4BDqaJuXKEit2y8ulXvTxCUAsBYojmG7RLUQyEd3OrlcZ4Lai+jeh/DkXmwTOTA/aSz2TCDOTWV1aEyhlaeTjcOPKMvYn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
